### ISSUE TITLE
Update Dashboard and Curation > Items item lists

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1045]
We could improve the look and scanability of the table that shows recent items (Dashboard) and the exhibit items (Curation > Items) if we update things to display small, regular-sized thumbnail images, plus update the columns class of the Title field. (I think the same partial is used in these two contexts.)

Below is an example of what I'm after. It's mostly CSS; I'm just not sure the best way to deal with updating the columns class of the Title field since it appears we're bring that in from Blacklight.

#### Current

![curation_-_curation_-_items___bob_fitch_photography_archive_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6604633/f737f9f6-c7e6-11e4-96f8-9709cea7a3ff.png)
-----

#### Improved

![curation_-_curation_-_items___bob_fitch_photography_archive_-_blacklight 2](https://cloud.githubusercontent.com/assets/101482/6604637/fe4140cc-c7e6-11e4-9f18-f44b80d8c5e7.png)
----

The update to the Title field is to either remove the `col-sm-9 col-lg-10` classes from the `h5` tag below, or change them to `col-sm-12`. This is to enable the title to extend the full width of its containing `td`, which will reduce the height of rows with longer titles.

````html
<h5 class="index_title col-sm-9 col-lg-10">
````

#### CSS used for "Improved" mockup

````css
#documents.table {
  font-size: $font-size-base;

  .document-thumbnail {
    border: none;
    margin-bottom: 0;
  }

  .document-thumbnail a > img {
    border: 1px solid $gray-light;
    width: 60px;
    height: 60px;
    object-fit: cover;
  }

  .document-counter {display: none;}

  .index_title {
    margin-top: $padding-small-vertical;
    margin-bottom: 0;
  }
}
````
