### ISSUE TITLE
Style default text for home, feature, and about pages

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#1101]
This is somewhat minor, but I think we could draw the curator's attention to default text block better by styling it to more clearly differentiate it from regular content on a page. Currently it looks like this:

![current](https://cloud.githubusercontent.com/assets/101482/6772714/4e2531ba-d0c1-11e4-8067-5a6768bf6cc6.png)
----

If we can add the `alert alert-info` classes on the div that surrounds the empty page text the blue alert styling will make it more clear that this is something the curator needs to attend to. In addition, the current styling of the heading and list could also use a little whitespace adjustment to make the list more readable (the code below assumes the div that surrounds the empty text has the following classes added to it: `empty-text-block alert alert-info`):

````scss
.empty-page-block {
  margin-top: $padding-large-vertical;
  h2 {
    margin-top: 0;
  }
  p, ol > li {
    padding: $padding-small-vertical;
  }
  ol > li:last-child {
    padding-bottom: 0;
  }
}
````

The results should look more or less like this:

![another_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6772747/15682fd4-d0c2-11e4-9db6-f384f28b3326.png)
----
![feature_page_one___another_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6772749/19ecbc00-d0c2-11e4-9744-76de3ce77a47.png)
----
![about_this_exhibit___another_exhibit_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6772751/1dd888f8-d0c2-11e4-9177-2ae009e9c1ea.png)
----
