### ISSUE TITLE
Add option for site masthead to have background image

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#909]

**Comment by ggeisler** [comment]
Below are details for displaying a background image in the masthead. The other part of this feature is giving the user a way to select and crop an image to use as the background image -- I'll add details about that once we resolve some decisions about our general approach to image selection and cropping.

The example SCSS below should work with the existing HTML used for the masthead (though I'd like to see the default height of the masthead be slightly smaller -- 120px instead of 131px) so I'm just providing the SCSS. The approach adjusts to any height masthead (assuming the source background image is tall enough, though there will be problems with the text fitting below 60px or so), and any amount of image blur (within reason; single digits). So in theory we should be able to provide the user with configuration options for both the blur amount and the masthead height.

Some example output:

Using the current default masthead height and 1px blur:

![maps-default](https://cloud.githubusercontent.com/assets/101482/6153606/9dffe1a4-b1da-11e4-8d84-3495b52a4547.png)

Same image but using a larger masthead height:

![maps-large](https://cloud.githubusercontent.com/assets/101482/6153629/cb34e7aa-b1da-11e4-859e-78b2c18bc247.png)

Different image:

![walters-default](https://cloud.githubusercontent.com/assets/101482/6153643/e5a93d8e-b1da-11e4-8e50-47a5680c8f02.png)

Different image with higher blur value:

![fitch-default-3px-blur](https://cloud.githubusercontent.com/assets/101482/6153773/e74ee912-b1db-11e4-8d23-36f2344385cc.png)

Extra small viewport, no blur:

![maps-xs-no-blur](https://cloud.githubusercontent.com/assets/101482/6153982/2de7120e-b1dd-11e4-8bca-2637bd1d47c5.png)

The SCSS code:

````scss
$masthead-height: 131px;
$masthead-image-blur: 1px;

#exhibit-masthead > .container {
  // Maintains the site title and subtitle at slightly below
  // vertically-centered, even if height of masthead is changed.
  position: relative;
  top: 60%;
  -webkit-transform: translateY(-50%);
  transform: translateY(-50%);
}

#exhibit-masthead {
  margin-bottom: 0;
  padding-top: 0;
  position: static;
  height: $masthead-height;
  width: 100%;
  // To handle potential text blurring caused by the "transform: translateY"
  // property in #exhibit-masthead > .container
  -webkit-transform-style: preserve-3d;
  -moz-transform-style: preserve-3d;
  transform-style: preserve-3d;

  .site-title {
    color: $white;
    text-shadow: 0 1px 0 $black;
  }
  small {
    color: $white;
    padding-top: $padding-base-vertical;
    @extend .hidden-xs;
  }
}

// This is to add a background image to the masthead, in a way that
// enables the site title and subtitle text to be visible above it.
#exhibit-masthead:before {
    content: "";
    position: absolute;
    left: 0;
    right: 0;
    display: block;
    width: auto;
    height: $masthead-height + $masthead-image-blur + 1;
    // Include gradient to improve text legibility,
    // especially on light background images.
    background-image:
     linear-gradient(
       rgba(0, 0, 0, 0.0),
       rgba(0, 0, 0, 0.4),
       rgba(0, 0, 0, 0.5)
     ), image-url("masthead/maps-2.jpg");
    background-repeat: no-repeat;
    // Add small amount of blur to help text stand out
    filter: url(masthead/blur.svg#blur); // for older versions of FF
    -webkit-filter: blur($masthead-image-blur);
    filter: blur($masthead-image-blur);
    // Shift image slightly to hide blurred edge of image
    margin-left: -$masthead-image-blur;
    margin-top: -$masthead-image-blur;
    overflow: hidden;
    // Add right border to image to hide lighter blurred edge
    border-right: 1px solid $black;
  }

@media screen and (max-width: $screen-xs-max) {
  $masthead-height: 65px;
  #topnav {
    padding-left: $padding-small-horizontal;
    padding-right: $padding-small-horizontal;
    width: 100%;
  }
  #exhibit-masthead {
    height: $masthead-height;
    .site-title {
      font-size: $font-size-h3;
      margin-top: $padding-base-horizontal * 2;
    }
  }
  #exhibit-masthead:before {
    height: $masthead-height + 1;
  }
}
````
