### ISSUE TITLE
New widget: Highlight browse categories

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#914]

**Comment by ggeisler** [comment]
Widget edit mode screenshot and considerations:

* Ideally the browse category image is a small square (CSS object fit for now, the user-cropped square later?)
* We should limit the checked items to five. If the exhibit is configured to show a sidebar, we really can only display three items. Not sure if we can determine that at widget edit time and set the limit dynamically, or if we want to just always use the limit of five and append a note to the widget instructions ("If the page to which you add this widget contains a sidebar, only the first three selected browse categories will be displayed.").

![curation_-_edit_page___beasts__amp__books_-_blacklight](https://cloud.githubusercontent.com/assets/101482/6046690/38fe6414-ac59-11e4-963f-4c26d0228676.png)

Widget display:

Screenshots below illustrate roughly how things should look at different viewport sizes. 

When the page has a sidebar:
* Show a maximum of three items
* If only one or two items, image size is 300px square
* If three items, image size is 220px square

If no sidebar:
* Show a maximum of five items
* Up to and including three items, image size is 300px square
* Four or five items, image size is 220px square

We can add the Bootstrap class `hidden-md` to the item container div of items that should be hidden at smaller viewports.

![sidebar-md](https://cloud.githubusercontent.com/assets/101482/6047095/5a433dae-ac5c-11e4-9180-59721998f8a2.png)

![sidebar-lg](https://cloud.githubusercontent.com/assets/101482/6047110/6d215f14-ac5c-11e4-9b54-19ad49ed0e4a.png)

![no-sidebar-md](https://cloud.githubusercontent.com/assets/101482/6047122/73c6280e-ac5c-11e4-9842-d78f6408c67d.png)

![no-sidebar-lg-max 4](https://cloud.githubusercontent.com/assets/101482/6047124/79778edc-ac5c-11e4-9a69-bd22ecbb1c8c.png)

![no-sidebar-lg-max 5](https://cloud.githubusercontent.com/assets/101482/6047129/7e4db332-ac5c-11e4-8bf3-ad3c704f21e5.png)

**Comment by ggeisler** [comment]
Some code that might help below. This approach uses background image for the images, which might not be ideal until we have user-cropped images to use, but this could be a start. (The flexbox-related CSS used for the multi-up widget should work similarly here.)

````html

 <div class="col-md-12">
    <div class="spotlight-flexbox">

      <div class="box">
        <div class="browse-category category-one">
          <div class="category-caption">
            <p class="category-title">
              Cape of Good Hope Plus Some Extra Words To Go To Third Line
            </p>
            <span class="item-count">
              99 items
            </span>
          </div>
        </div>
      </div>

    <!-- Additional "box" divs for subsequent items -->
````

````scss
.browse-category {
  background-size: cover;
  border: 2px solid #b3b3b3;
  border-radius: 7px;
  width: 300px;
  height: 300px;
  position: relative;
  float: left;
  &.category-five {
    width: 220px;
    height: 220px;
  }
}
.category-caption {
  color: #f7f7f7;
  position: absolute;
  bottom: 20px;
  text-align: center;
  text-shadow: 0 1px 0 #000000;
  width: 100%;
}
.category-title {
  font-size: 18px;
  line-height: 1.2;
  margin: 0;
  padding: 6px;
}
.item-count {
  font-size: 14px;
  text-transform: uppercase;
}
.category-one {
  background-image:
  linear-gradient(
    rgba(0, 0, 0, 0.0),
    rgba(0, 0, 0, 0.1),
    rgba(0, 0, 0, 0.5)
  ), image-url("exhibits/fitch.png");
}

````
