### ISSUE TITLE
New widget: Image grid with associated text block

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#917]

**Comment by ggeisler** [comment]
Widget requires seven images to be selected, plus a heading and text block. The curator could omit a heading or text and I think the widget will still look fine. The heading/text block is on the left side by default, but can be floated right with a configuration option. There is also an option to show a border above the widget; I suggest this is not checked by default, but could be a nice option when the widget is added after another widget.

Basic implementation below (see [this mockup](http://web.stanford.edu/~geisler/spotlight/image-grid/image-grid-alternate-no-flexbox.html) for how it looks at different viewport sizes):

![text-images-grid-left](https://cloud.githubusercontent.com/assets/101482/6338638/1eeb260a-bb65-11e4-81b6-3dac33c38ac4.png)

---
Here's an  example where the curator is using the widget twice on a page, to show how it looks with the text on the right and the border option selected:

![text-images-grid-two](https://cloud.githubusercontent.com/assets/101482/6338659/484c6874-bb65-11e4-94f6-da8545b19e7a.png)

---
For the CSS image cropping (object-fit) to look okay on older browsers, I suggest we try to use the polyfill here: https://github.com/anselmh/object-fit though I haven't actually tried it (that should be the only older browser/cross-browser concern with this implementation).

---
For configuration, maybe something like below. I'm not showing it, but the "Selected items" text inputs should be draggable for reordering, but we don't need checkboxes associated with them, since all images are required (whether we enforce that or not is an open question; I don't mind if we don't, since the curator should see that it doesn't look right without all images, though I suppose it would be nice if we did enforce it).

For the Text box, ideally we would support Markdown or otherwise enable the user to compose multiple paragraphs; if that's difficult, I think it would be okay to postpone that for future work (if we decide it is important enough).

![widget-configuration](https://cloud.githubusercontent.com/assets/101482/6338701/94a55582-bb65-11e4-8434-dfb066b3e45b.png)

## Example code
Below is the code I used for the [mockup](http://web.stanford.edu/~geisler/spotlight/image-grid/image-grid-alternate-no-flexbox.html). Feel free to do something different, this is just here in case it saves time figuring things out:

````html
          <div class="image-grid-widget">
            <div class="text-col col-md-3">
              <h3>The Bob Fitch Archive</h3>
              <p>
                Between 1968 and 1974, Bob Fitch photographed union organizing activities and for nearly 2 years was staff photographer for the Southern Christian Leadership Conference (SCLC) of which Dr. Martin Luther King Jr. was president.
              </p>
              <p>
                This exhibit is a digital collection of a selection of Bob Fitch's photographs, featuring Cesar Chavez and Dr. Martin Luther King. Jr.
              </p>
            </div>
            <div class="images-col col-md-9">
              <div class="row top">
                <div class="col-sm-5 col-xs-12 box">
                  <a href="#">
                    <img src="../images/image-grid/fitch/03.jpg"/>
                  </a>
                </div>
                <div class="col-sm-3 col-xs-12 box">
                  <a href="#">
                    <img src="../images/image-grid/fitch/01.jpg"/>
                  </a>
                </div>
                <div class="col-sm-4 col-xs-12 box">
                  <a href="#">
                    <img src="../images/image-grid/fitch/09.jpg"/>
                  </a>
                </div>
              </div>

              <div class="row bottom hidden-xs">
                <div class="col-sm-3 box">
                  <a href="#">
                    <img src="../images/image-grid/fitch/02.jpg"/>
                  </a>
                </div>
                <div class="col-sm-3 box">
                  <a href="#">
                    <img src="../images/image-grid/fitch/04.jpg"/>
                  </a>
                </div>
                <div class="col-sm-3 box">
                  <a href="#">
                    <img src="../images/image-grid/fitch/06.jpg"/>
                  </a>
                </div>
                <div class="col-sm-3 box">
                  <a href="#">
                    <img src="../images/image-grid/fitch/08.jpg"/>
                  </a>
                </div>
              </div>
            </div>
````

I added a class of `border` to the `image-grid-widget` class to show the border above the widget. I added a class of `right` to the `text-col` class to make the text float to the right. 

````scss
.image-grid-widget {
  &.border {border-top: 1px solid $gray-lighter;}
  margin: ($padding-large-vertical * 2) auto;
  padding-top: $padding-large-vertical;
  .text-col {
    padding-left: 0;
    h3 {
      margin-top: 0;
    }
    &.right {
      float: right;
      padding-right: 0;
      padding-left: $padding-large-horizontal;
    }
  }
  .images-col {
    div {
      height: 100%;
      padding: 0 $padding-xs-horizontal 0;
    }

    .row > div:last-child {
      padding-right: 0;
    }

    .row.top {
      height: 220px;
      @media (min-width: $screen-lg-min) {
        height: 240px;
      }
    }

    .row.bottom {
      height: 120px;
      margin-top: $padding-large-vertical;
      @media (min-width: $screen-lg-min) {
        height: 135px;
      }
    }
    img {
      border: 1px solid $gray-light;
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
  }

  @media (max-width: $screen-sm-max) {
    .row.top div {margin: $padding-base-vertical 0;}
    .images-col {padding-left: $padding-xs-horizontal;}
    .text-col.right {padding-left: 0;}
  }

  @media (max-width: $screen-xs-max) {
    .images-col .box {
      text-align: center;
      img {max-width: 400px;}
    }
  }
}

````
