### ISSUE TITLE
Exhibity-style browse landing page

### ISSUE THREAD

**Issue by ggeisler** [sul-dlss/spotlight#918]
Related to #786

**Comment by ggeisler** [comment]
I'm assuming that we want to offer the exhibity-style (I'm now thinking of this as "museum-style" unless something better comes to us) browse landing page as an alternative to the current version, though maybe after we see how the app feels with some of the design improvements we can revisit that. To keep it simple, we could just display this new browse landing page when the "Museum-style" option is checked:

![museum-style-setting](https://cloud.githubusercontent.com/assets/101482/6364128/d55bea7c-bc56-11e4-9291-b1a3c3aa3a28.png)

----
I created a [mockup](http://web.stanford.edu/~geisler/spotlight/browse/browse-landing-page.html) to capture the basic idea for the layout and styling but feel free to modify as makes sense in integrating this with the exiting code. In this mockup, the first three items have an ideally-sized image (as we might have if we add a cropping feature for the browse categories later; in this ticket I'm assuming we're just using the item image as is -- `_thumb` size would work for our SU implementation) and the second three are more randomly-size images, as we get if we just take the image associated with the item (that's why the fifth item is not as tall as the others).

![browse-landing-page-museum-style](https://cloud.githubusercontent.com/assets/101482/6364308/b66bb672-bc58-11e4-9970-5e24e12e659f.png)

----
![browse-landing-page](https://cloud.githubusercontent.com/assets/101482/6364309/be3151dc-bc58-11e4-8d59-c4b58d903680.gif)
----

Below is roughly the code I used in the [mockup](http://web.stanford.edu/~geisler/spotlight/browse/browse-landing-page.html), in case it helps. I'm assuming we'll just create a new partial to switch to when the museum-style setting is on, so the example code below is not based on any of the current browse landing page html or css. So if you take a different approach you might have to modify accordingly.

### HTML

The only dynamic parts are image, title, and item count.

````html
          <div class="browse-landing">
            <div class="col-sm-4 col-xs-12">
              
             <!-- Start of first item -->
              <a href="#"> <!-- link to browse detail page for this item -->
                <div class="image-overlay">
                  <img src="../images/browse/maps/01.jpg" class="img-responsive" />
                  <div class="text-overlay">
                    <h2 class="browse-category-title">
                      This is Category One's Title, a Bit Longer
                      <small>99 items</small>
                    </h2>
                  </div>
                </div>
              </a>
            </div>
           <!-- end of first item -->
           
            <div class="col-sm-4 col-xs-12">
            <a href="#">
              <div class="image-overlay">
                <img src="../images/browse/maps/02.jpg" class="img-responsive" />
                <div class="text-overlay">
                  <h2 class="browse-category-title">
                    Category Two's Title
                    <small>24 items</small>
                  </h2>
                </div>
              </div>
            </a>
            </div>

 <!-- other items follow using same code blocks as above -->
````

### SCSS

````scss
.browse-landing {

  // Placeholder for vertically alignment - might already be available from use in another feature 
  %vertical-align {
    position: relative;
    top: 50%;
    transform: translateY(-50%);
  }

  .image-overlay {
    position: relative;
    margin-bottom: $padding-large-vertical * 3;
    max-height: 240px;
    border-radius: $border-radius-large;
    border: 2px solid $gray-light;
    overflow: hidden;
  }

  .text-overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.4));
    color: $white;
    padding: 8%;
    text-align: center;
    text-shadow: 0 1px 0 $black;
    // prevents potential blur caused by the vertical-align technique
    transform-style: preserve-3d;

    .browse-category-title {
      font-size: $font-size-h3;
      @extend %vertical-align;

      small {
        display: block;
        color: $white;
        margin-top: $padding-large-vertical;
        text-transform: uppercase;
      }
    }

    &:hover {
      linear-gradient(to bottom, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.7));
    }
  }

  @media screen and (max-width: $screen-xs-max) {
    .image-overlay {
      margin: 10px auto;
      max-width: 350px;
    }
    .text-overlay .browse-category-title {font-size: $font-size-h3;}
  }
  @media screen and (min-width: $screen-sm-min) and (max-width: $screen-md-max) {
    .text-overlay .browse-category-title {font-size: $font-size-h4;}
  }
  @media screen and (min-width: $screen-sm-min) and (max-width: $screen-sm-max) {
    .image-overlay {max-height: 180px;}
  }
  @media screen and (min-width: $screen-lg-min) {
    .image-overlay {max-height: 300px;}
  }
}
````
